services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/vendor
    stdin_open: true
    tty: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=aws-1-eu-central-1.pooler.supabase.com
      - DB_PORT=6543
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres.ymasedycdgyroiwouqya
      - DB_PASSWORD=1pQH4jxqgFOkgJxq
      - DB_SSLMODE=require
  vite:
    image: node:20
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"